name: Build and Run Apptainer

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Apptainer
          run: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:apptainer/ppa
            sudo apt-get update
            sudo apt-get install -y apptainer

        - name: Build Apptainer image
          run: |
            ls -lah
            apptainer build crpropa.sif crpropa.def

        # from https://github.com/elgohr/Github-Release-Action
        - name: Create Release
          id: create_release
          uses: elgohr/Github-Release-Action@v5
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            title: ${{ github.event.head_commit.timestamp }}
            tag: ${{ github.run_id }}

        # from https://github.com/softprops/action-gh-release
        - name: Release
          uses: softprops/action-gh-release@v2
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: crpropa.sif